// client/packages/fidscript-instant-vue/src/components/SignedIn.vue
<script setup lang="ts">
import type { InstantSchemaDef } from '@fidscript/instant-sdk';
import type { InstantVueDatabase } from '../InstantVueDatabase.js';

const props = defineProps<{
  db: InstantVueDatabase<InstantSchemaDef<any, any, any>, boolean>;
}>();

const { isLoading, error, user } = props.db.useAuth();
</script>

<template>
  <slot v-if="!isLoading && !error && user" />
</template>

// client/packages/fidscript-instant-svelte/src/lib/SignedIn.svelte
<script lang="ts">
  import type { InstantSchemaDef } from '@fidscript/instant-sdk';
  import type { InstantSvelteDatabase } from './InstantSvelteDatabase.svelte.js';
  import type { Snippet } from 'svelte';

  let { db, children }: {
    db: InstantSvelteDatabase<InstantSchemaDef<any, any, any>>;
    children: Snippet;
  } = $props();

  // svelte-ignore state_referenced_locally
  const auth = db.useAuth();
</script>

{#if !auth.isLoading && !auth.error && auth.user}
  {@render children()}
{/if}
